[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[functions."weekly-recap"]
  schedule = "0 17,18 * * 0"

[functions."daily-push"]
  schedule = "0 4,5 * * *"

[functions."daily-session"]
  schedule = "0 2,3 * * *"
